version: "1"
services:
  hello:
    build:
      context: ./hello
    ports:
      - "3000:3000"
    networks:
      - app-network
  kello:
    build:
      context: ./kello
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
