version: "1"
services:
  hello:
    build:
      context: ./Hello
    ports:
      - "80:3000"
    networks:
      - app-network
  kello:
    build:
      context: ./Kello
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
