pipeline {
    agent any

    tools {
        nodejs '20.13.1' // Use the configured Node.js version
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                   dir('Hello'){
                    sh 'npm install'
                   }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                  dir('Hello'){
                    sh 'npm test'
                  }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sshagent(credentials:['topdevs_clone']) {
                        // Ensure the .ssh directory exists and then add the host key to known_hosts
                        sh """
                        mkdir -p ~/.ssh
                        ssh-keyscan -H 40.90.234.213 >> ~/.ssh/known_hosts
                        """

                        // Deployment commands
                        sh """
                        ssh azureuser@40.90.234.213 'mkdir -p /jenkin/Hello'
                        rsync -avz --delete --exclude="node_modules" ./ azureuser@40.90.234.213:/jenkin/Hello
                        ssh azureuser@40.90.234.213 'cd /jenkin/Hello && npm install && npm start'
                        """
                    }
                }
            }
        }
    }
}
