pipeline {
    agent any

    tools {
        nodejs '20.13.1' // Use the configured Node.js version
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                   dir('Hello'){
                    sh 'npm install'
                   }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                  dir('Hello'){
                    sh 'npm test'
                  }
                }
            }
        }

        stage('Run Application') {
            steps {
                script {
                  dir('Hello'){
                    sh 'npm start'
                  }
                }
            }
        }
    }
}
